<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TradePartner;

class TradePartnerSeeder extends Seeder
{
    public function run(): void
    {
        $partners = [
            ['ZIMU', 'ZIM INTEGRATED SHIPPING SERVICES LTD'],
            ['YML-ST-PAU', 'CAMERON, LYNCH AND WILLIAMS'],
            ['XMN', 'XIAMEN AIRLINE'],
            ['WWSU', 'WESTWOOD SHIPPING LINES INC'],
            ['WLWH', 'WALLENIUS WILHELMSEN'],
            ['WH1415', 'SMALL, CRUZ AND POWERS'],
            ['WH1414', 'COOK, KIM AND JONES'],
            ['WH1413', 'DIAZ-CRUZ'],
            ['WH1412', 'BENSON-KELLY'],
            ['WH1411', 'GONZALEZ, JOHNSON AND HAMILTON'],
            ['WH1410', 'LEON AND SONS'],
            ['WH1409', 'GOLDEN, FISHER AND ABBOTT'],
            ['WH1408', 'THOMAS-THOMAS'],
            ['WH1407', 'MOORE, KIM AND PHILLIPS'],
            ['WH1406', 'KEY-ROSE'],
            ['WH1405', 'HOLT, BARAJAS AND BUSH'],
            ['WH1404', 'DAVIS-HOLLAND'],
            ['WH1403', 'ROBINSON, JACKSON AND GONZALEZ'],
            ['WH1402', 'LAMB-CUNNINGHAM'],
            ['WH1401', 'GILL-PRUITT'],
            ['WH1400', 'WILEY LLC'],
            ['WH1399', 'HUGHES PLC'],
            ['WH1398', 'PHILLIPS, MEZA AND PATEL'],
            ['WH1397', 'STEWART-NORRIS'],
            ['WH1393', 'SANCHEZ, MOORE AND SMITH'],
            ['WH1392', 'EVANS-SMITH'],
            ['WH1391', 'TRUJILLO GROUP'],
            ['WH1390', 'COX-PHILLIPS'],
            ['WH1391', 'TRUJILLO GROUP'],
            ['WH1390', 'COX-PHILLIPS'],
            ['WH1389', 'VELAZQUEZ-WALLACE'],
            ['WH1388', 'PEREZ, YOUNG AND WEBB'],
            ['WH1387', 'MUNOZ-SIMMONS'],
            ['WH1386', 'MANNING, GARCIA AND SMITH'],
            ['WH1385', 'ROSALES, LEE AND HANCOCK'],
            ['WH1372', 'SCHWARTZ-DOYLE'],
            ['WH1371', 'ELLISON, KING AND JACKSON'],
            ['WH1370', 'COOPER GROUP (74)'],
            ['WH1369', 'NGUYEN-GILL'],
            ['WH1368', 'HANSEN, SANTANA AND SANDERS'],
            ['WH1367', 'PADILLA, HILL AND HODGES'],
            ['WH1366', 'COLLINS LTD'],
            ['WH1365', 'ROBERTSON-VALENCIA'],
            ['WH1364', 'SPEARS-GEORGE'],
            ['WH1363', 'MARSHALL, THOMAS AND GONZALEZ'],
            ['WH1362', 'KRAMER, HERRERA AND SHARP'],
            ['WH1361', 'LEWIS-MAY'],
            ['WH1360', 'CROSBY GROUP'],
            ['WH1359', 'EVERETT, RIVAS AND ROCHA'],
            ['WH1358', 'GARCIA-MARTINEZ'],
            ['WH1357', 'HARRIS-WALKER'],
            ['WH1356', 'OBRIEN-ALVARADO'],
            ['WH1355', 'VARGAS, CAMPBELL AND BUSH'],
            ['WH1354', 'TAYLOR-MAXWELL'],
            ['WH1353', 'MORGAN, JOHNSON AND GARZA'],
            ['WH1348', 'NASH, GIBSON AND GEORGE'],
            ['WH1347', 'MENDOZA LLC'],
            ['WH1346', 'BALDWIN, CRUZ AND ADAMS'],
            ['WH1343', 'ST. GEORGE WAREHOUSE'],
            ['WH1334', 'ERICKSON INC'],
            ['WH1333', 'STEWART-HICKS'],
            ['WH1331', 'GOODWIN-HARRIS'],
            ['WH1330', 'AVILA, ORTIZ AND RIOS'],
            ['WH1328', 'WILSON-LANE'],
            ['WH1327', 'MCKNIGHT AND SONS'],
            ['WH1326', 'MURPHY, FROST AND GONZALEZ'],
            ['WH1325', 'ALEXANDER-RYAN'],
            ['WH1324', 'GORDON, FLYNN AND MORALES'],
            ['WH1322', 'JONES, BOYD AND REYNOLDS'],
            ['WH1321', 'FOWLER-WILLIS'],
            ['WH1320', 'SMITH, SMITH AND PRATT'],
            ['WH1319', 'MAYER, DENNIS AND FRANCO'],
            ['WH1318', 'HAYNES-ANDREWS'],
            ['WH1317', 'COMBS-FIGUEROA'],
            ['WH1316', 'SOSA-ROBBINS'],
            ['WH1315', 'FREEMAN, BELL AND JOHNSON'],
            ['WH1314', 'ADAMS-LIU'],
            ['WH1313', 'TURNER-GARNER'],
            ['WH1312', 'LAMB, HICKS AND GREEN'],
            ['WH1311', 'HUGHES-BURNS'],
            ['WH1310', 'MACK, GUZMAN AND MORAN'],
            ['WH1309', 'NOVAK LLC'],
            ['WH1308', 'MILLS-JOHNSON'],
            ['WH1307', 'SANCHEZ, GOLDEN AND HENDERSON'],
            ['WH1306', 'BRENNAN INC'],
            ['WH1305', 'OCONNOR AND SONS'],
            ['WH1304', 'CARPENTER-MITCHELL'],
            ['WH1303', 'CHRISTENSEN, WILLIAMS AND ROGERS'],
            ['WH1302', 'GARDNER, ORTIZ AND BOWERS'],
            ['WH1301', 'PONCE, SIMMONS AND DIAZ'],
            ['WH1300', 'CABRERA-SANCHEZ'],
            ['WH1299', 'MADDOX GROUP'],
            ['WH1298', 'HESTER-BROWN'],
            ['WH1297', 'PARKER, AUSTIN AND SCHULTZ'],
            ['WH1296', 'ANTHONY-NORMAN'],
            ['WH1295', 'HODGES-MILLER'],
            ['WH1294', 'SCOTT, WALSH AND JOHNSON'],
            ['WH1293', 'SCOTT-BURKE'],
            ['WH1292', 'DAVIS, ALVAREZ AND SAVAGE'],
            ['WH1291', 'CARSON-WEBB'],
            ['WH1290', 'SCHWARTZ, ANDERSON AND FERNANDEZ'],
            ['WH1289', 'PENA-TORRES'],
            ['WH1288', 'CONNER, SMITH AND COLLINS'],
            ['WH1287', 'THOMPSON-CONRAD'],
            ['WH1286', 'RHODES, BENSON AND BROWN'],
            ['WH1284', 'PINEDA, JONES AND CARPENTER'],
            ['WH1283', 'PHILLIPS, WILLIAMS AND STEWART'],
            ['WH1282', 'DAVIS-WILLIAMS'],
            ['WH1281', 'LONG-BROWN'],
            ['WH1280', 'SHAFFER, ROBERTSON AND HALL'],
            ['WH1279', 'BLAIR, RUSSELL AND KING'],
            ['WH1278', 'NORRIS LTD'],
            ['WH1277', 'DUFFY LLC'],
            ['WH1276', 'PATTON-WU'],
            ['WH1274', 'DELGADO-MORALES'],
            ['WH1273', 'FIELDS-ADKINS'],
            ['WH1272', 'LEE, SCHNEIDER AND MATA'],
            ['WH1271', 'WARD, THOMPSON AND RAMSEY'],
            ['WH1270', 'AUSTIN-COOK'],
            ['WH1268', 'REEVES, MCDONALD AND GREEN'],
            ['WH1267', 'SCHNEIDER, MILLER AND SMITH'],
            ['WH1266', 'GONZALES, KIDD AND WARREN'],
            ['WH1265', 'TRAN-WILLIAMS'],
            ['WH1263', 'HOLLAND-WILLIAMS'],
            ['WH1262', 'LOWE, CAIN AND RAMIREZ'],
            ['WH1261', 'OCHOA-HOLT'],
            ['WH1260', 'GONZALEZ, WISE AND HENDERSON'],
            ['WH1259', 'HORTON-HULL'],
            ['WH1258', 'JENKINS AND SONS'],
            ['WH1256', 'NOBLE-POWELL'],
            ['WH1255', 'RICE INC'],
            ['WH1253', 'ROACH, REYNOLDS AND VANCE'],
            ['WH1252', 'ARMSTRONG-MARTIN'],
            ['WH1250', 'RIVERA, SANDERS AND CROSBY'],
            ['WH1249', 'NORMAN, LOPEZ AND WILLIAMS'],
            ['WH1248', 'HERRING INC'],
            ['WH1246', 'OWENS-BANKS'],
            ['WH1245', 'MCCOY-RIVAS'],
            ['WH1244', 'BROWN, SNYDER AND HATFIELD'],
            ['WH1243', 'COLLINS, AVILA AND DAVIS'],
            ['WH1242', 'DIXON, FISCHER AND HOLMES'],
            ['WH1241', 'MONROE, ODONNELL AND COLLIER'],
            ['WH1239', 'YORK-MCCLAIN'],
            ['WH1238', 'FORD, CRUZ AND RODRIGUEZ'],
            ['WH1237', 'REYNOLDS-MILLER'],
            ['WH1236', 'WILCOX, MOORE AND ADKINS'],
            ['WH1235', 'HUNTER-ROGERS'],
            ['WH1234', 'COOK-HUGHES'],
            ['WH1233', 'DAY-MARTINEZ'],
            ['WH1231', 'PETERSEN PLC'],
            ['WH1230', 'SCHAEFER GROUP'],
            ['WH1229', 'CARTER PLC'],
            ['WH1228', 'GRANT, TANNER AND GONZALEZ'],
            ['WH1227', 'REEVES-THOMAS'],
            ['WH1226', 'PHELPS PLC'],
            ['WH1225', 'COLEMAN-STUART'],
            ['WH1224', 'HARRIS-ATKINSON'],
            ['WH1223', 'BURNETT-RHODES'],
            ['WH1222', 'CLARKE, SLOAN AND MARTINEZ'],
            ['WH1221', 'CORTEZ, HOWARD AND DANIELS'],
            ['WH1220', 'CHAVEZ-ELLIOTT'],
            ['WH1219', 'LONG-SINGLETON'],
            ['WH1217', 'TREVINO, WRIGHT AND JOHNSON'],
            ['WH1216', 'WASHINGTON, HERNANDEZ AND GOODMAN'],
            ['WH1215', 'SMITH, MERCER AND GONZALES'],
            ['WH1214', 'OAKLAND INT\'L CONTAINER TERMINAL'],
            ['WH1212', 'BLAKE-BAKER'],
            ['WH1211', 'LOPEZ, GONZALEZ AND MURRAY'],
            ['WH1210', 'WOODWARD, LEE AND LEWIS'],
            ['WH1209', 'STONE, PRICE AND LEE'],
            ['WH1208', 'HERNANDEZ, FLORES AND ROSE'],
            ['WH1206', 'CUEVAS-BAKER'],
            ['WH1205', 'CHEN, COOK AND WONG'],
            ['WH1203', 'FISCHER, WEEKS AND MYERS'],
            ['WH1202', 'LYONS, HALEY AND PERRY'],
            ['WH1201', 'WHITE, NELSON AND ROY'],
            ['WH1200', 'CLAY-LARSON'],
            ['WH1199', 'RILEY-BENNETT'],
            ['WH1197', 'MILLS, PARKER AND LOPEZ'],
            ['WH1196', 'BROWN-BOYER'],
            ['WH1194', 'MILLER, KIM AND ROGERS'],
            ['WH1193', 'DAVIS-BOND'],
            ['WH1191', 'YOUNG-BEAN'],
            ['WH1190', 'DILLON AND SONS'],
            ['WH1188', 'ANDREWS GROUP'],
            ['WH1187', 'MUELLER, GARCIA AND MORRIS'],
            ['WH1186', 'DILLON-ONEILL'],
            ['WH1185', 'LEWIS, OWENS AND WRIGHT'],
            ['WH1184', 'SERRANO-COX'],
            ['WH1183', 'ROBERTS-PARKS'],
            ['WH1182', 'SCHULTZ INC'],
            ['WH1181', 'SIMS PLC'],
            ['WH1180', 'LONG BEACH CONTAINER PIER F'],
            ['WH1178', 'KELLEY-WRIGHT'],
            ['WH1177', 'HOGAN-JOHNSON'],
            ['WH1176', 'WBCT TERMINAL-Y773'],
            ['WH1175', 'DIAZ GROUP'],
            ['WH1173', 'MURRAY-FREEMAN'],
            ['WH1171', 'REED, HERMAN AND NORTON'],
            ['WH1170', 'DAWSON, SMITH AND VALDEZ'],
            ['WH1168', 'VASQUEZ, LOPEZ AND DANIELS'],
            ['WH1167', 'GARNER-OBRIEN'],
        ];

        foreach ($partners as $partner) {
            TradePartner::updateOrCreate(
                ['code' => $partner[0]],
                [
                    'name' => $partner[1],
                    'type' => str_starts_with($partner[0], 'WH') ? 'WAREHOUSE' : 'CARRIER',
                    'status' => 'BUSINESS',
                    'country_id' => 1,
                ]
            );
        }
    }
}
